name: Harsha
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build-step
        run: |
          echo "ur app is built"
          echo "ur app is built"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: build-step
        run: |
          echo "ur app is built"
          echo "ur app is built"
  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
    - name: build-step
      run: |
        echo "ur app is built"
        echo "ur app is built"
