name: Harsha
on: 
  push:
    branches:
      - main    
  pull_trigger:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build-step
        run: |
          echo "pull was successful"
