name: Harsha

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: build-step
        run: |
          echo "ur app is built"
          echo "ur app is built"
   deploy:
     runs-on: ubuntu-latest
    
     steps:
       - name: build-step
         run: |
           echo "ur app is built"
           echo "ur app is built"
  
  
